[env:esp32dev]
platform = espressif32@6.9.0
board = esp32dev
framework = espidf
monitor_speed = 115200

lib_deps =
    espressif/esp_lvgl_port@^2.3.0   ; 固定版本避免API变动
    espressif/esp_i2c_bus@^1.0.0     ; 提供 i2c_bus_create 函数
